### ISSUE TITLE
Map.nlogo

### ISSUE THREAD

**Issue by phillips199** [abmgis/abmgis#1]
The file map.nlogo seems to be corrupt.  Error message when opening file is "NetLogo can't open file the model /path/to/file/map.nlogo."  as well as "Unable to open the model /path/to/file/map.nlogo."  This is related to the Uganda Example in the book "Agent-Based Modelling & Geographical Information Systems".  Thanks.

**Comment by acrooks2** [comment]
I just checked this with NetLogo 6.1 and it works for me.

**Comment by phillips199** [comment]
Thanks, I was not downloading it correctly from GitHub. It works for me now.

**Comment by acrooks2** [comment]
Great
