### ISSUE TITLE
Missing link Appendix A10 - Modeling Transportation and Development for Reston, VA

### ISSUE THREAD

**Issue by vvseva** [abmgis/abmgis#2]
Hey!
Dear authors,

At the page [Appendix A10 - Modeling Transportation and Development for Reston, VA](https://github.com/abmgis/abmgis/tree/master/AppendixA/Reston#appendix-a10---modeling-transportation-and-development-for-reston-va )

line Model Available at: Here.
"Here" is unfortunately missing a link.

Could you please help me to find that model of transportation and development by Swartz.

Best regards,
Seva

**Comment by acrooks2** [comment]
Thanks for pointing this out. This has now been fixed.
